
#服务端发送到客户端的命令
exports.CLIENT_WANT_TOMAIN = "CLIENT_WANT_TOMAIN"
exports.CLIENT_WANT_TOMENU = "CLIENT_WANT_TOMENU"
exports.CLIENT_WANT_MENU_CLASS = "CLIENT_WANT_MENU_CLASS"
exports.CLIENT_WANT_MENU = "CLIENT_WANT_MENU"
exports.CLIENT_WANT_ORDER_LIST = "CLIENT_WANT_ORDER_LIST"
exports.CLIENT_WANT_BIG_IMAGE = "CLIENT_WANT_BIG_IMAGE"
exports.CLIENT_WANT_SMALL_IMAGE = "CLIENT_WANT_SMALL_IMAGE"
exports.CLIENT_WANT_ADDED_ORDER = "CLIENT_WANT_ADDED_ORDER"
exports.CLIENT_WANT_PAYMENT = "CLIENT_WANT_PAYMENT"

exports.CLIENT_GET_ONLINE_LIST = "CLIENT_GET_ONLINE_LIST" #服务台用
exports.CLIENT_WANT_ONLINE_LIST = "CLIENT_WANT_ONLINE_LIST" #服务台用
exports.CLIENT_WANT_REPORT_DAY = "CLIENT_WANT_REPORT_DAY" #服务台用
exports.CLIENT_WANT_REPORT_MONTH = "CLIENT_WANT_REPORT_MONTH" #服务台用
exports.CLIENT_WANT_CLIENT_LIST = "CLIENT_WANT_CLIENT_LIST" #服务台用
exports.CLIENT_WANT_SELECTED_MENU_CLASS = "CLIENT_WANT_SELECTED_MENU_CLASS" #服务台用
exports.CLIENT_WANT_ORDER_DETAIL = "CLIENT_WANT_ORDER_DETAIL" #服务台用

#客户端发送到服务端的命令
exports.SERV_CHK_CLIENT = "SERV_CHK_CLIENT"
exports.SERV_MENU_CLASS_LIST = "SERV_MENU_CLASS_LIST"
exports.SERV_MENU_LIST = "SERV_MENU_LIST"
exports.SERV_ORDER_LIST = "SERV_ORDER_LIST"
exports.SERV_BIG_IMAGE = "SERV_BIG_IMAGE"
exports.SERV_SMALL_IMAGE = "SERV_SMALL_IMAGE"
exports.SERV_ADD_ORDER = "SERV_ADD_ORDER"
exports.SERV_PAYMENT = "SERV_PAYMENT"

exports.SERV_OPEN_CLIENT = "SERV_OPEN_CLIENT"
exports.SERV_CLOSE_CLIENT = "SERV_CLOSE_CLIENT"

#客户端发送到服务端的命令（服务台用的）
exports.SERV_ONLINE_LIST = "SERV_ONLINE_LIST"
exports.SERV_REPORT_DAY = "SERV_REPORT_DAY"
exports.SERV_REPORT_MONTH = "SERV_REPORT_MONTH"
exports.SERV_CLIENT_LIST = "SERV_CLIENT_LIST"
exports.SERV_CLIENT_ADD = "SERV_CLIENT_ADD"
exports.SERV_CLIENT_DELETE = "SERV_CLIENT_DELETE"
exports.SERV_MENU_CLASS_ADD = "SERV_MENU_CLASS_ADD"
exports.SERV_MENU_CLASS_DELETE = "SERV_MENU_CLASS_DELETE"
exports.SERV_MENU_ADD = "SERV_MENU_ADD"
exports.SERV_MENU_DELETE = "SERV_MENU_DELETE"
exports.SERV_ORDER_DETAIL = "SERV_ORDER_DETAIL"
exports.SERV_ORDER_DETAIL_CHANGE_STATUS = "SERV_ORDER_DETAIL_CHANGE_STATUS"
