
//服务端发送到客户端的命令
var CLIENT_WANT_TOMAIN = "CLIENT_WANT_TOMAIN";

//客户端发送到服务端的命令
var SERV_CHK_CLIENT = "SERV_CHK_CLIENT";
var SERV_MENU_CLASS_LIST = "SERV_MENU_CLASS_LIST";
var SERV_MENU_LIST = "SERV_MENU_LIST";
var SERV_ORDER_LIST = "SERV_ORDER_LIST";
var SERV_BIG_IMAGE = "SERV_BIG_IMAGE";
var SERV_SMALL_IMAGE = "SERV_SMALL_IMAGE";
var SERV_ADD_ORDER = "SERV_ADD_ORDER";
var SERV_PAYMENT = "SERV_PAYMENT";
var SERV_ISEND_CLIENT = "SERV_ISEND_CLIENT";

//服务台发送到服务端的命令
var SERV_OPEN_CLIENT = "SERV_OPEN_CLIENT";
var SERV_CLOSE_CLIENT = "SERV_CLOSE_CLIENT";

exports.CLIENT_WANT_TOMAIN = CLIENT_WANT_TOMAIN;

exports.SERV_CHK_CLIENT = SERV_CHK_CLIENT;
exports.SERV_MENU_CLASS_LIST = SERV_MENU_CLASS_LIST;
exports.SERV_MENU_LIST = SERV_MENU_LIST;
exports.SERV_ORDER_LIST = SERV_ORDER_LIST;
exports.SERV_BIG_IMAGE = SERV_BIG_IMAGE;
exports.SERV_SMALL_IMAGE = SERV_SMALL_IMAGE;
exports.SERV_ADD_ORDER = SERV_ADD_ORDER;
exports.SERV_PAYMENT = SERV_PAYMENT;
exports.SERV_ISEND_CLIENT = SERV_ISEND_CLIENT;

exports.SERV_OPEN_CLIENT = SERV_OPEN_CLIENT;
exports.SERV_CLOSE_CLIENT = SERV_CLOSE_CLIENT;
