
//服务端发送到客户端的命令
exports.CLIENT_WANT_TOMAIN = "CLIENT_WANT_TOMAIN";
exports.CLIENT_WANT_TOMENU = "CLIENT_WANT_TOMENU";
exports.CLIENT_WANT_ONLINE_LIST = "CLIENT_WANT_ONLINE_LIST"; //服务台用

//客户端发送到服务端的命令
exports.SERV_CHK_CLIENT = "SERV_CHK_CLIENT";
exports.SERV_MENU_CLASS_LIST = "SERV_MENU_CLASS_LIST";
exports.SERV_MENU_LIST = "SERV_MENU_LIST";
exports.SERV_ORDER_LIST = "SERV_ORDER_LIST";
exports.SERV_BIG_IMAGE = "SERV_BIG_IMAGE";
exports.SERV_SMALL_IMAGE = "SERV_SMALL_IMAGE";
exports.SERV_ADD_ORDER = "SERV_ADD_ORDER";
exports.SERV_PAYMENT = "SERV_PAYMENT";
exports.SERV_ISEND_CLIENT = "SERV_ISEND_CLIENT";

//客户端发送到服务端的命令（服务台用的）
exports.SERV_ONLINE_LIST = "SERV_ONLINE_LIST";

//服务台发送到服务端的命令
exports.SERV_OPEN_CLIENT = "SERV_OPEN_CLIENT";
exports.SERV_CLOSE_CLIENT = "SERV_CLOSE_CLIENT";
